services:
  url-storage:
    build: ./services/url-storage # 新建的URL Master项目目录
    container_name: url-storage
    hostname: url-storage
    ports:
      - "8000:8000" # 暴露HTTP接口
    networks:
      - yuban_net
    # command: [ "python", '/app/src/app.py' ]
    command: tail -f /dev/null
    depends_on:
      - url-manager
    environment:
      - PYTHONPATH=/app/src/grpc:/app/src
    volumes:
      - type: bind
        source: ./services/url-storage/data
        target: /app/data # 持久化存储URL状态
      - type: bind
        source: ./services/url-storage/src
        target: /app/src/ #开发的时候同步代码
      - type: bind
        source: ./services/grpc/
        target: /app/grpc/

  url-manager:
    build: ./services/url-manager
    container_name: url-manager
    hostname: url-manager
    ports:
      - "8001:8001"
    networks:
      - yuban_net
    command: tail -f /dev/null
    environment:
      - PYTHONPATH=/app/grpc:/app/src
    volumes:
      - type: bind
        source: ./services/url-manager/src
        target: /app/src/ #开发的时候同步代码
      - type: bind
        source: ./services/grpc/
        target: /app/grpc/

  spider-node:
    build: ./services/spiders
    container_name: spiders-1
    hostname: spiders-1
    ports:
      - "8002:8001"
    networks:
      - yuban_net
    command: tail -f /dev/null
    environment:
      - PYTHONPATH=/app/grpc:/app/src
    volumes:
      - type: bind
        source: ./services/grpc/
        target: /app/grpc
      - type: bind
        source: ./services/spiders/src
        target: /app/src/
    #   python2:
    #     build: ./services/spiders
    #     container_name: spidernode2
    #     networks:
    #       - zk-kafka-net
    #     environment:
    #       - KAFKA_BOOTSTRAP_SERVERS=kaf1:9092
    #       - URL_MASTER=http://url-master:8000
    #     depends_on:
    #       kafka:
    #         condition: service_healthy
    #       kafka-init:  # 新增依赖
    #         condition: service_completed_successfully
    #     command: tail -f /dev/null

    #   python3:
    #     build: ./services/spiders
    #     container_name: spidernode3
    #     networks:
    #       - zk-kafka-net
    #     environment:
    #       - KAFKA_BOOTSTRAP_SERVERS=kaf1:9092
    #       - URL_MASTER=http://url-master:8000
    #     depends_on:
    #       kafka:
    #         condition: service_healthy
    #       kafka-init:  # 新增依赖
    #         condition: service_completed_successfully
    #     command: tail -f /dev/null

    # volumes:
    #   zookeeper_data:
    #     driver: local
    #   kafka_data:
    #     driver: local
    #   url_storage:
    #     driver: local

networks:
  yuban_net:
    driver: bridge
