services:
  url-storage:
    build: ./services/url-storage # 新建的URL Master项目目录
    container_name: url-storage
    hostname: url-storage
    ports:
      - "8000:8000" # 暴露HTTP接口
    networks:
      - yuban_net
#    command: [ "python", '/app/src/app.py' ]
    command: tail -f /dev/null
    depends_on:
      - url-manager
    environment:
      - PYTHONPATH=/app/src/grpc:/app/src
    volumes:
      - type: bind
        source: ./services/url-storage/data
        target: /app/data # 持久化存储URL状态
      - type: bind
        source: ./services/url-storage/src
        target: /app/src/ #开发的时候同步代码
      - type: bind
        source: ./services/grpc/
        target: /app/grpc/

  url-manager:
    build: ./services/url-manager
    container_name: url-manager
    hostname: url-manager
    ports:
      - "8001:8001"
    networks:
      - yuban_net
    command: tail -f /dev/null
    environment:
      - PYTHONPATH=/app/grpc:/app/src
    volumes:
      - type: bind
        source: ./services/url-manager/src
        target: /app/src/ #开发的时候同步代码
      - type: bind
        source: ./services/grpc/
        target: /app/grpc/

  spider-node1:
    build: ./services/spiders
    container_name: spiders-1
    hostname: spiders-1
    depends_on:
      - url-manager
      - down_disk
    ports:
      - "8002:8001"
    networks:
      - yuban_net
    command: tail -f /dev/null
    environment:
      - PYTHONPATH=/app/grpc:/app/src
    volumes:
      - type: bind
        source: ./services/grpc/
        target: /app/grpc
      - type: bind
        source: ./services/spiders/src
        target: /app/src/

  spider-node2:
    build: ./services/spiders
    container_name: spiders-2
    hostname: spiders-2
    depends_on:
      - url-manager
      - down_disk
    ports:
      - "8003:8001"
    networks:
      - yuban_net
    command: tail -f /dev/null
    environment:
      - PYTHONPATH=/app/grpc:/app/src
    volumes:
      - type: bind
        source: ./services/grpc/
        target: /app/grpc
      - type: bind
        source: ./services/spiders/src
        target: /app/src/

  down_disk:
    build: ./services/spiders
    container_name: down-disk
    hostname: down-disk
    ports:
      - "8080:8001"
    networks:
      - yuban_net
    command: tail -f /dev/null
    environment:
      - PYTHONPATH=/app/grpc:/app/src
    volumes:
      - type: bind
        source: ./services/grpc/
        target: /app/grpc
      - type: bind
        source: ./services/data-storage/src
        target: /app/src/
      - type: bind
        source: ./services/data-storage/binary_data
        target: /app/binary_data/

#  experiment:
#    build: ./services/experiment
#    container_name: experiment
#    hostname: experiment
#    ports:
#      - "9000:8001"
#    networks:
#      - yuban_net
#    command: tail -f /dev/null
#    environment:
#      - PYTHONPATH=/app/grpc:/app/src
#    volumes:
#      - type: bind
#        source: ./services/grpc/
#        target: /app/grpc
#      - type: bind
#        source: ./services/experiment/src
#        target: /app/src/

networks:
  yuban_net:
    driver: bridge
