# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import Dvrpc_pb2 as Dvrpc__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in Dvrpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class URLManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushURL = channel.unary_unary(
                '/URLManager/PushURL',
                request_serializer=Dvrpc__pb2.PushURLRequest.SerializeToString,
                response_deserializer=Dvrpc__pb2.PushURLReply.FromString,
                _registered_method=True)
        self.Registe = channel.unary_unary(
                '/URLManager/Registe',
                request_serializer=Dvrpc__pb2.RegisteRequest.SerializeToString,
                response_deserializer=Dvrpc__pb2.RegisteResponse.FromString,
                _registered_method=True)


class URLManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PushURL(self, request, context):
        """url-manager的服务，接受flask的url并回应完成接收
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Registe(self, request, context):
        """接受爬虫节点的注册并返回自己的ip
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_URLManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushURL': grpc.unary_unary_rpc_method_handler(
                    servicer.PushURL,
                    request_deserializer=Dvrpc__pb2.PushURLRequest.FromString,
                    response_serializer=Dvrpc__pb2.PushURLReply.SerializeToString,
            ),
            'Registe': grpc.unary_unary_rpc_method_handler(
                    servicer.Registe,
                    request_deserializer=Dvrpc__pb2.RegisteRequest.FromString,
                    response_serializer=Dvrpc__pb2.RegisteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'URLManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('URLManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class URLManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PushURL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/URLManager/PushURL',
            Dvrpc__pb2.PushURLRequest.SerializeToString,
            Dvrpc__pb2.PushURLReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Registe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/URLManager/Registe',
            Dvrpc__pb2.RegisteRequest.SerializeToString,
            Dvrpc__pb2.RegisteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SpidersNodeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Heartbeat = channel.unary_unary(
                '/SpidersNode/Heartbeat',
                request_serializer=Dvrpc__pb2.HeartbeatQuery.SerializeToString,
                response_deserializer=Dvrpc__pb2.HeartbeatReply.FromString,
                _registered_method=True)
        self.DistributeURL = channel.unary_unary(
                '/SpidersNode/DistributeURL',
                request_serializer=Dvrpc__pb2.DistributeURLRequest.SerializeToString,
                response_deserializer=Dvrpc__pb2.DistributeURLResponse.FromString,
                _registered_method=True)


class SpidersNodeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Heartbeat(self, request, context):
        """spider的服务段，接受url-manager的heartebeat和url并做出应答
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DistributeURL(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpidersNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=Dvrpc__pb2.HeartbeatQuery.FromString,
                    response_serializer=Dvrpc__pb2.HeartbeatReply.SerializeToString,
            ),
            'DistributeURL': grpc.unary_unary_rpc_method_handler(
                    servicer.DistributeURL,
                    request_deserializer=Dvrpc__pb2.DistributeURLRequest.FromString,
                    response_serializer=Dvrpc__pb2.DistributeURLResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SpidersNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('SpidersNode', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SpidersNode(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SpidersNode/Heartbeat',
            Dvrpc__pb2.HeartbeatQuery.SerializeToString,
            Dvrpc__pb2.HeartbeatReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DistributeURL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SpidersNode/DistributeURL',
            Dvrpc__pb2.DistributeURLRequest.SerializeToString,
            Dvrpc__pb2.DistributeURLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FileTransferStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadFolder = channel.stream_unary(
                '/FileTransfer/UploadFolder',
                request_serializer=Dvrpc__pb2.FolderChunk.SerializeToString,
                response_deserializer=Dvrpc__pb2.UploadStatus.FromString,
                _registered_method=True)


class FileTransferServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadFolder(self, request_iterator, context):
        """客户端流式上传文件夹
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileTransferServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadFolder': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFolder,
                    request_deserializer=Dvrpc__pb2.FolderChunk.FromString,
                    response_serializer=Dvrpc__pb2.UploadStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FileTransfer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('FileTransfer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileTransfer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadFolder(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/FileTransfer/UploadFolder',
            Dvrpc__pb2.FolderChunk.SerializeToString,
            Dvrpc__pb2.UploadStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
