# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Dvrpc.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'Dvrpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x44vrpc.proto\"\x1d\n\x0ePushURLRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\"\x1d\n\x0cPushURLReply\x12\r\n\x05reply\x18\x01 \x01(\t\"(\n\x0eRegisteRequest\x12\x16\n\x0e\x63ontainer_name\x18\x01 \x01(\t\"\"\n\x0fRegisteResponse\x12\x0f\n\x07\x63ore_ip\x18\x01 \x01(\t\"#\n\x14\x44istributeURLRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\"&\n\x15\x44istributeURLResponse\x12\r\n\x05reply\x18\x01 \x01(\x08\"\x1f\n\x0eHeartbeatQuery\x12\r\n\x05query\x18\x01 \x01(\t\"\x1f\n\x0eHeartbeatReply\x12\r\n\x05reply\x18\x01 \x01(\t2i\n\nURLManager\x12+\n\x07PushURL\x12\x0f.PushURLRequest\x1a\r.PushURLReply\"\x00\x12.\n\x07Registe\x12\x0f.RegisteRequest\x1a\x10.RegisteResponse\"\x00\x32\x80\x01\n\x0bSpidersNode\x12/\n\tHeartbeat\x12\x0f.HeartbeatQuery\x1a\x0f.HeartbeatReply\"\x00\x12@\n\rDistributeURL\x12\x15.DistributeURLRequest\x1a\x16.DistributeURLResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Dvrpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUSHURLREQUEST']._serialized_start=15
  _globals['_PUSHURLREQUEST']._serialized_end=44
  _globals['_PUSHURLREPLY']._serialized_start=46
  _globals['_PUSHURLREPLY']._serialized_end=75
  _globals['_REGISTEREQUEST']._serialized_start=77
  _globals['_REGISTEREQUEST']._serialized_end=117
  _globals['_REGISTERESPONSE']._serialized_start=119
  _globals['_REGISTERESPONSE']._serialized_end=153
  _globals['_DISTRIBUTEURLREQUEST']._serialized_start=155
  _globals['_DISTRIBUTEURLREQUEST']._serialized_end=190
  _globals['_DISTRIBUTEURLRESPONSE']._serialized_start=192
  _globals['_DISTRIBUTEURLRESPONSE']._serialized_end=230
  _globals['_HEARTBEATQUERY']._serialized_start=232
  _globals['_HEARTBEATQUERY']._serialized_end=263
  _globals['_HEARTBEATREPLY']._serialized_start=265
  _globals['_HEARTBEATREPLY']._serialized_end=296
  _globals['_URLMANAGER']._serialized_start=298
  _globals['_URLMANAGER']._serialized_end=403
  _globals['_SPIDERSNODE']._serialized_start=406
  _globals['_SPIDERSNODE']._serialized_end=534
# @@protoc_insertion_point(module_scope)
